# Generated by Django 5.2.3 on 2025-07-01 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('graduates_view', 'عرض الخريجين'), ('graduates_create', 'إضافة خريجين'), ('graduates_edit', 'تعديل الخريجين'), ('graduates_delete', 'حذف الخريجين'), ('graduates_export', 'تصدير بيانات الخريجين'), ('surveys_view', 'عرض الاستبيانات'), ('surveys_create', 'إنشاء استبيانات'), ('surveys_edit', 'تعديل الاستبيانات'), ('surveys_delete', 'حذف الاستبيانات'), ('surveys_responses', 'عرض إجابات الاستبيانات'), ('reports_view', 'عرض التقارير'), ('reports_create', 'إنشاء تقارير'), ('reports_export', 'تصدير التقارير'), ('users_manage', 'إدارة المستخدمين'), ('permissions_manage', 'إدارة الصلاحيات'), ('system_settings', 'إعدادات النظام')], max_length=100, unique=True, verbose_name='اسم الصلاحية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'سجل النشاط', 'verbose_name_plural': 'سجلات النشاط'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='description',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='وكيل المستخدم'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنصب'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التوقيت'),
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'نسخة كاملة'), ('incremental', 'نسخة تدريجية'), ('manual', 'نسخة يدوية')], max_length=20, verbose_name='نوع النسخة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('running', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'سجل النسخ الاحتياطي',
                'verbose_name_plural': 'سجلات النسخ الاحتياطي',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('notification_type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ'), ('system', 'نظام')], default='info', max_length=20, verbose_name='نوع الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستقبل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.permission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('department', models.CharField(max_length=100, verbose_name='القسم')),
                ('position', models.CharField(max_length=100, verbose_name='المنصب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق')], default='active', max_length=20, verbose_name='الحالة')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee', verbose_name='المدير المباشر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
            },
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنح')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='accounts.employee', verbose_name='الموظف')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منح بواسطة')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.permission', verbose_name='الصلاحية')),
            ],
            options={
                'verbose_name': 'صلاحية موظف',
                'verbose_name_plural': 'صلاحيات الموظفين',
                'unique_together': {('employee', 'permission')},
            },
        ),
    ]
