# Generated by Django 5.2.3 on 2025-06-29 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الودجت')),
                ('widget_type', models.CharField(choices=[('counter', 'عداد'), ('chart', 'رسم بياني'), ('table', 'جدول'), ('progress', 'شريط تقدم'), ('list', 'قائمة')], max_length=20, verbose_name='نوع الودجت')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('query', models.TextField(verbose_name='الاستعلام')),
                ('position_x', models.IntegerField(default=0, verbose_name='الموضع الأفقي')),
                ('position_y', models.IntegerField(default=0, verbose_name='الموضع العمودي')),
                ('width', models.IntegerField(default=4, verbose_name='العرض')),
                ('height', models.IntegerField(default=3, verbose_name='الارتفاع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='فترة التحديث بالثواني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'ودجت لوحة التحكم',
                'verbose_name_plural': 'ودجتات لوحة التحكم',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('graduates_summary', 'ملخص الخريجين'), ('employment_status', 'حالة التوظيف'), ('survey_responses', 'استجابات الاستبيانات'), ('graduation_trends', 'اتجاهات التخرج'), ('salary_analysis', 'تحليل الرواتب'), ('geographic_distribution', 'التوزيع الجغرافي'), ('custom', 'تقرير مخصص')], max_length=30, verbose_name='نوع التقرير')),
                ('description', models.TextField(blank=True, verbose_name='وصف التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('filter_graduation_year_start', models.IntegerField(blank=True, null=True, verbose_name='سنة التخرج من')),
                ('filter_graduation_year_end', models.IntegerField(blank=True, null=True, verbose_name='سنة التخرج إلى')),
                ('filter_college', models.CharField(blank=True, max_length=100, verbose_name='الكلية')),
                ('filter_major', models.CharField(blank=True, max_length=100, verbose_name='التخصص')),
                ('filter_employment_status', models.CharField(blank=True, max_length=20, verbose_name='حالة التوظيف')),
                ('filter_gender', models.CharField(blank=True, max_length=10, verbose_name='الجنس')),
                ('filter_city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('auto_refresh', models.BooleanField(default=False, verbose_name='تحديث تلقائي')),
                ('refresh_interval_days', models.IntegerField(default=7, verbose_name='فترة التحديث بالأيام')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='التكرار')),
                ('recipients', models.TextField(verbose_name='المستقبلون (بريد إلكتروني)')),
                ('next_run', models.DateTimeField(verbose_name='التشغيل التالي')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.report')),
            ],
            options={
                'verbose_name': 'تقرير مجدول',
                'verbose_name_plural': 'التقارير المجدولة',
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=100, verbose_name='مفتاح البيانات')),
                ('data_value', models.TextField(verbose_name='قيمة البيانات')),
                ('data_type', models.CharField(choices=[('json', 'JSON'), ('text', 'نص'), ('number', 'رقم'), ('chart', 'رسم بياني')], default='json', max_length=20, verbose_name='نوع البيانات')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنتاج')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='reports.report')),
            ],
            options={
                'verbose_name': 'بيانات التقرير',
                'verbose_name_plural': 'بيانات التقارير',
                'unique_together': {('report', 'data_key')},
            },
        ),
    ]
