# Generated by Django 5.2.3 on 2025-06-29 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('text', 'نص'), ('textarea', 'نص طويل'), ('radio', 'اختيار من متعدد'), ('checkbox', 'اختيار متعدد'), ('select', 'قائمة منسدلة'), ('number', 'رقم'), ('email', 'بريد إلكتروني'), ('date', 'تاريخ'), ('rating', 'تقييم')], max_length=20, verbose_name='نوع السؤال')),
                ('is_required', models.BooleanField(default=False, verbose_name='مطلوب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='نص المساعدة')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='نص الخيار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question')),
            ],
            options={
                'verbose_name': 'خيار السؤال',
                'verbose_name_plural': 'خيارات الأسئلة',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاستبيان')),
                ('description', models.TextField(verbose_name='وصف الاستبيان')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('closed', 'مغلق')], default='draft', max_length=10, verbose_name='حالة الاستبيان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('google_form_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط جوجل فورم')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'استبيان',
                'verbose_name_plural': 'الاستبيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_complete', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='graduates.graduate')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'استجابة الاستبيان',
                'verbose_name_plural': 'استجابات الاستبيانات',
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'graduate')},
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القالب')),
                ('description', models.TextField(verbose_name='وصف القالب')),
                ('category', models.CharField(default='عام', max_length=100, verbose_name='الفئة')),
                ('difficulty', models.CharField(default='متوسط', max_length=50, verbose_name='الصعوبة')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب استبيان',
                'verbose_name_plural': 'قوالب الاستبيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_token', models.CharField(max_length=100, unique=True, verbose_name='رمز الدعوة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('opened', 'تم الفتح'), ('completed', 'تم الإكمال'), ('expired', 'منتهي الصلاحية')], default='pending', max_length=20, verbose_name='حالة الدعوة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الفتح')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_invitations', to='graduates.graduate')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'دعوة استبيان',
                'verbose_name_plural': 'دعوات الاستبيانات',
                'ordering': ['-created_at'],
                'unique_together': {('survey', 'graduate')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='إجابة نصية')),
                ('answer_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجابة رقمية')),
                ('answer_date', models.DateField(blank=True, null=True, verbose_name='إجابة تاريخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('selected_choices', models.ManyToManyField(blank=True, to='surveys.questionchoice', verbose_name='الخيارات المحددة')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'unique_together': {('response', 'question')},
            },
        ),
    ]
