# Generated by Django 5.2.3 on 2025-07-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='auto_send',
            field=models.BooleanField(default=False, verbose_name='إرسال تلقائي بعد الإنشاء'),
        ),
        migrations.AddField(
            model_name='survey',
            name='email_message',
            field=models.TextField(blank=True, verbose_name='رسالة البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='survey',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='موضوع البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='survey',
            name='send_method',
            field=models.CharField(choices=[('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب'), ('both', 'كليهما')], default='email', max_length=10, verbose_name='طريقة الإرسال'),
        ),
        migrations.AddField(
            model_name='survey',
            name='whatsapp_message',
            field=models.TextField(blank=True, verbose_name='رسالة الواتساب'),
        ),
    ]
