# Generated by Django 5.2.3 on 2025-07-02 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_allow_null_fields'),
        ('surveys', '0002_survey_auto_send_survey_email_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email_sent',
            field=models.IntegerField(default=0, verbose_name='عدد رسائل البريد المرسلة'),
        ),
        migrations.AddField(
            model_name='survey',
            name='responses_received',
            field=models.IntegerField(default=0, verbose_name='عدد الاستجابات المستلمة'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('template', 'من قالب جاهز'), ('google_forms', 'Google Forms'), ('custom', 'مخصص')], default='custom', max_length=20, verbose_name='نوع الاستبيان'),
        ),
        migrations.AddField(
            model_name='survey',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم القالب'),
        ),
        migrations.AddField(
            model_name='survey',
            name='total_sent',
            field=models.IntegerField(default=0, verbose_name='إجمالي المرسل إليهم'),
        ),
        migrations.AddField(
            model_name='survey',
            name='whatsapp_sent',
            field=models.IntegerField(default=0, verbose_name='عدد رسائل الواتساب المرسلة'),
        ),
        migrations.CreateModel(
            name='SurveySendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_method', models.CharField(choices=[('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب'), ('both', 'كليهما')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('delivered', 'تم التسليم'), ('read', 'تم القراءة')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.graduate')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'سجل إرسال استبيان',
                'verbose_name_plural': 'سجلات إرسال الاستبيانات',
                'ordering': ['-sent_at'],
            },
        ),
    ]
