# Generated by Django 5.2.3 on 2025-07-03 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_add_survey_type_and_statistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='سنة التخرج')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='التخصص')),
                ('college', models.CharField(blank=True, max_length=100, verbose_name='الكلية')),
                ('degree', models.CharField(blank=True, max_length=100, verbose_name='الدرجة العلمية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('target_college', models.CharField(blank=True, max_length=100, null=True, verbose_name='الكلية المستهدفة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'خريج',
                'verbose_name_plural': 'خريجون',
                'ordering': ['-graduation_year', 'full_name'],
            },
        ),
    ]
