# Generated by Django 5.2.3 on 2025-07-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_graduate'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='survey_logos/', verbose_name='شعار الجهة'),
        ),
        migrations.AddField(
            model_name='survey',
            name='org_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الجهة'),
        ),
    ]
