# Generated by Django 5.2.3 on 2025-07-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_allow_null_fields'),
        ('surveys', '0005_survey_logo_survey_org_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinvitation',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الرمز المميز'),
        ),
        migrations.AlterField(
            model_name='surveyinvitation',
            name='graduate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.graduate'),
        ),
        migrations.AlterField(
            model_name='surveyinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('opened', 'تم الفتح'), ('completed', 'تم الإكمال'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة الدعوة'),
        ),
    ]
