# Generated by Django 5.2.3 on 2025-06-29 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الجامعي')),
                ('degree', models.CharField(choices=[('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('diploma', 'دبلوم')], max_length=20, verbose_name='الدرجة العلمية')),
                ('major', models.CharField(max_length=100, verbose_name='التخصص')),
                ('college', models.CharField(max_length=100, verbose_name='الكلية')),
                ('graduation_year', models.IntegerField(verbose_name='سنة التخرج')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='المعدل التراكمي')),
                ('employment_status', models.CharField(choices=[('employed', 'موظف'), ('unemployed', 'غير موظف'), ('self_employed', 'عمل حر'), ('student', 'طالب')], max_length=20, verbose_name='حالة التوظيف')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب')),
                ('work_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العمل')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='السعودية', max_length=100, verbose_name='الدولة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خريج',
                'verbose_name_plural': 'الخريجون',
                'ordering': ['-graduation_year', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GraduateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='graduates.graduate')),
            ],
            options={
                'verbose_name': 'ملاحظة خريج',
                'verbose_name_plural': 'ملاحظات الخريجين',
                'ordering': ['-created_at'],
            },
        ),
    ]
