# Generated by Django 5.2.3 on 2025-06-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='country',
            field=models.CharField(blank=True, default='السعودية', max_length=100, null=True, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('diploma', 'دبلوم')], max_length=20, null=True, verbose_name='الدرجة العلمية'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'موظف'), ('unemployed', 'غير موظف'), ('self_employed', 'عمل حر'), ('student', 'طالب')], max_length=20, null=True, verbose_name='حالة التوظيف'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='المعدل التراكمي'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة التخرج'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
